/*
 * FrameTesteRandomico.java
 *
 * Created on 1 de Junho de 2008, 13:26
 *
 * Copyright (C) 2008 Source Forge, Inc.
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License 
 * as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public 
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 *
 * Comments only in english, portuguese, spanish or french
 * 
 * Authors: Antonio Neto <tomsalvador at users.sourceforge.net>
 */

package AntaresDSM;

import javax.swing.JOptionPane;

/**
 *
 * @author  Tom
 */
public class FrameNovo extends javax.swing.JDialog {
    private DSM dsm;
    
    
    /** Creates new form FrameTesteRandomico */
    public FrameNovo() {
        initComponents();
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Código Gerado ">//GEN-BEGIN:initComponents
    private void initComponents() {
        edNDeVertices = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edPopulacao = new javax.swing.JTextField();
        btnGerar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edDependenciasMultiplas = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Nova DSM");
        edNDeVertices.setText("0");
        edNDeVertices.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edNDeVerticesActionPerformed(evt);
            }
        });

        jLabel1.setText("Quantidade de elementos da matriz (0 para rand\u00f4mico):");

        jLabel2.setText("Popula\u00e7\u00e3o dos elementos da matriz de 0 a 10:");

        jLabel3.setText("(0 rand\u00f4mico, 1 vazia, 2 baixa popula\u00e7\u00e3o, 10 alta popula\u00e7\u00e3o)");

        edPopulacao.setText("0");

        btnGerar.setText("Gerar");
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        jLabel4.setText("Aceita depend\u00eancias maiores que 1:");

        jLabel5.setText("(0 n\u00e3o, 1 sim)");

        edDependenciasMultiplas.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edPopulacao)
                            .addComponent(edNDeVertices, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(64, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(282, 282, 282)
                                    .addComponent(edDependenciasMultiplas, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(258, 258, 258))
                                .addComponent(btnGerar, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(95, 95, 95))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edNDeVertices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edPopulacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(edDependenciasMultiplas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addComponent(btnGerar)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-373)/2, (screenSize.height-266)/2, 373, 266);
    }// </editor-fold>//GEN-END:initComponents

    private void edNDeVerticesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edNDeVerticesActionPerformed
// TODO adicione seu código de manipulação aqui:
    }//GEN-LAST:event_edNDeVerticesActionPerformed

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
// TODO adicione seu código de manipulação aqui:
        int nDeVertices, populacao, nDependenciasMultiplas;
        boolean dependenciasMultiplas;
        
        try {
            nDeVertices = Integer.parseInt(edNDeVertices.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Todos os valores devem ser numéricos.","Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            populacao = Integer.parseInt(edPopulacao.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Todos os valores devem ser numéricos.","Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            nDependenciasMultiplas = Integer.parseInt(edDependenciasMultiplas.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Todos os valores devem ser numéricos.","Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if( nDeVertices < 0 ){
            JOptionPane.showMessageDialog(null,"Número de vértices inválido.","Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if( populacao <0 || populacao > 10 ){
            JOptionPane.showMessageDialog(null,"População inválida.","Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if( nDependenciasMultiplas == 0 ){
            dependenciasMultiplas = false;
        }else if( nDependenciasMultiplas == 1 ){
            dependenciasMultiplas = true;
        }else{
            JOptionPane.showMessageDialog(null,"Valor inválido para dependências múltiplas.","Erro", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        dsm = new DSM(nDeVertices, populacao, dependenciasMultiplas);
        
        this.setVisible(false);
        
    }//GEN-LAST:event_btnGerarActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameNovo().setVisible(true);
            }
        });
    }
    
    // Declaração de variáveis - não modifique//GEN-BEGIN:variables
    private javax.swing.JButton btnGerar;
    private javax.swing.JTextField edDependenciasMultiplas;
    private javax.swing.JTextField edNDeVertices;
    private javax.swing.JTextField edPopulacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // Fim da declaração de variáveis//GEN-END:variables

    public DSM getDsm() {
        return dsm;
    }

    public void setDsm(DSM dsm) {
        this.dsm = dsm;
    }
    
}
