/*
 * FrameTesteRandomico.java
 *
 * Created on 1 de Junho de 2008, 13:26
 *
 * Copyright (C) 2008 Source Forge, Inc.
 * 
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public License 
 * as published by the Free Software Foundation; either
 * version 3 of the License, or (at your option) any later version.
 * 
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Library General Public License for more details.
 * 
 * You should have received a copy of the GNU Lesser General Public 
 * License along with this library; if not, write to the
 * Free Software Foundation, Inc., 51 Franklin Street, Fifth Floor,
 * Boston, MA 02110-1301, USA.
 *
 * Comments only in english, portuguese, spanish or french
 * 
 * Authors: Antonio Neto <tomsalvador at users.sourceforge.net>
 */

package AntaresDSM;

import javax.swing.JOptionPane;

/**
 *
 * @author  Tom
 */
public class NewFrame extends javax.swing.JDialog {
    private DSM dsm;
    
    
    /** Creates new form FrameTesteRandomico */
    public NewFrame() {
        initComponents();
    }
    
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        edVertexNumber = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edPopulation = new javax.swing.JTextField();
        btnGenerate = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        edMultipleDependecies = new javax.swing.JTextField();

        setTitle("New DSM");

        edVertexNumber.setText("0");
        edVertexNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edVertexNumberActionPerformed(evt);
            }
        });

        jLabel1.setText("Amount of elements in the matrix (0 for random):");

        jLabel2.setText("Population of elements in the matrix from 0 to 10:");

        jLabel3.setText("(0 random, 1 empty, 2 low population, 10 high population)");

        edPopulation.setText("0");

        btnGenerate.setText("Generate");
        btnGenerate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateActionPerformed(evt);
            }
        });

        jLabel4.setText("Accept dependencies bigger than 1:");

        jLabel5.setText("(0 no, 1 yes)");

        edMultipleDependecies.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(edPopulation)
                            .addComponent(edVertexNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(282, 282, 282)
                                    .addComponent(edMultipleDependecies, javax.swing.GroupLayout.DEFAULT_SIZE, 56, Short.MAX_VALUE))
                                .addComponent(btnGenerate, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(95, 95, 95))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addContainerGap(277, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(edVertexNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(edPopulation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(edMultipleDependecies, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addGap(26, 26, 26)
                .addComponent(btnGenerate)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel2.getAccessibleContext().setAccessibleName("Population of elements in the matrix from 0 to 10:");

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-373)/2, (screenSize.height-266)/2, 373, 266);
    }// </editor-fold>//GEN-END:initComponents

    private void edVertexNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edVertexNumberActionPerformed
// TODO add your manipulation code here:
    }//GEN-LAST:event_edVertexNumberActionPerformed

    private void btnGenerateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateActionPerformed
// TODO add your manipulation code here:
        int vertexAmount, population, numberOfMultipleDependencies;
        boolean multipleDependencies;
        
        try {
            vertexAmount = Integer.parseInt(edVertexNumber.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Values must be numeric.","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            population = Integer.parseInt(edPopulation.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Values must be numeric.","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        try {
            numberOfMultipleDependencies = Integer.parseInt(edMultipleDependecies.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"Values must be numeric.","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if( vertexAmount < 0 ){
            JOptionPane.showMessageDialog(null,"Number of vertex is not valid.","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if( population <0 || population > 10 ){
            JOptionPane.showMessageDialog(null,"Population is not valid.","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if( numberOfMultipleDependencies == 0 ){
            multipleDependencies = false;
        }else if( numberOfMultipleDependencies == 1 ){
            multipleDependencies = true;
        }else{
            JOptionPane.showMessageDialog(null,"Number of multiple dependencies is not valid.","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        dsm = new DSM(vertexAmount, population, multipleDependencies);
        
        this.setVisible(false);
        
    }//GEN-LAST:event_btnGenerateActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new NewFrame().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerate;
    private javax.swing.JTextField edMultipleDependecies;
    private javax.swing.JTextField edPopulation;
    private javax.swing.JTextField edVertexNumber;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables

    public DSM getDsm() {
        return dsm;
    }

    public void setDsm(DSM dsm) {
        this.dsm = dsm;
    }
    
}
